/**
 * The following code is generated by D&A UI Framework.
 * It is not expected to be modified by developers.
 * Any modification may paralyze the form.!!
 * So we strongly recommend that you do not change any thing of this file.!!
 */
 
 
package com.jiuqi.dna.training.mahan.ui;

import com.jiuqi.dna.ui.wt.widgets.FormControls;
import com.jiuqi.dna.ui.wt.widgets.Composite;
import com.jiuqi.dna.ui.wt.widgets.Label;
import com.jiuqi.dna.ui.wt.widgets.Text;
import com.jiuqi.dna.ui.wt.widgets.Spinner;
import com.jiuqi.dna.ui.custom.combo.ComboList;
import com.jiuqi.dna.ui.custom.combo.DatePicker;
import com.jiuqi.dna.ui.wt.widgets.ComboPanel;
import com.jiuqi.dna.ui.wt.widgets.Button;


public class AddStuffPageControls extends FormControls{
	public Composite cmp_1;
	public Label lbl_name;
	public Text txt_name;
	public Label lbl_staffAge;
	public Spinner spr_age;
	public Label lbl_sex;
	public ComboList cbl_sex;
	public Label lbl_date;
	public DatePicker dap_date;
	public Label lbl_deptId;
	public ComboPanel cop_dept;
	public Label lbl_remark;
	public Text txt_remark;
	public Composite cmp_2;
	public Composite cmp_3;
	public Button btn_add;
	public Button btn_cancel;
	public Button btn_addSave;
	
}