/**
 * The following code is generated by D&A UI Framework.
 * It is not expected to be modified by developers.
 * Any modification may paralyze the form.!!
 * So we strongly recommend that you do not change any thing of this file.!!
 */
 
 
package com.jiuqi.dna.training.mahan.ui;

import com.jiuqi.dna.ui.wt.widgets.FormControls;
import com.jiuqi.dna.ui.wt.widgets.Composite;
import com.jiuqi.dna.ui.wt.widgets.ToolBar;
import com.jiuqi.dna.ui.wt.widgets.ToolItem;
import com.jiuqi.dna.ui.wt.widgets.SashForm;
import com.jiuqi.dna.ui.wt.widgets.Label;


public class DefaultPageControls extends FormControls{
	public Composite cmp_1;
	public ToolBar tbr_1;
	public ToolItem tbi_Add;
	public ToolItem tbi_Update;
	public ToolItem tbi_Delete;
	public ToolItem tbi_Up;
	public ToolItem tbi_Down;
	public ToolItem tbi_Close;
	public Composite cmp_2;
	public SashForm saf_1;
	public Composite cmp_3;
	public Composite cmp_select;
	public Label lbl_select_name;
	public Composite cmp_search;
	public Composite cmp_show;
	public Composite cmp_table;
	public Composite cmp_paginate;
	
}