/**
 * The following code is generated by D&A UI Framework.
 * It is not expected to be modified by developers.
 * Any modification may paralyze the form.!!
 * So we strongly recommend that you do not change any thing of this file.!!
 */
 
 
package com.jiuqi.dna.training.mahan.ui;

import com.jiuqi.dna.ui.wt.widgets.FormControls;
import com.jiuqi.dna.ui.wt.widgets.Button;


public class HelloDNAControls extends FormControls{
	public Button btn_1;
	
}